AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 20
    Environment:
      Variables:
        AWS_SES_ACCESS_KEY_ID: !Ref SesAccessKeyId
        AWS_SES_SECRET_ACCESS_KEY: !Ref SesSecretAccessKey
        AWS_SES_REGION: !Ref  SesRegion
        DB_HOST: !Ref DbHost
        DB_USER: !Ref DbUser
        DB_PASSWORD: !Ref DbPassword
        DB_DATABASE: !Ref DbDatabase
        COIN_GEKO_API_KEY: !Ref CoinGekoApiKey

Parameters:
  SesAccessKeyId:
    Type: String
  SesSecretAccessKey:
    Type: String
  SesRegion:
    Type: String
  EmailFrom:
    Type: String
  DbHost:
    Type: String
  DbUser:
    Type: String
  DbPassword:
    Type: String
  DbDatabase:
    Type: String
  CoinGekoApiKey:
    Type: String

Resources:
  CryptoSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      FunctionName: CryptoSearchFunction
      Handler: src/main.searchCryptoHistory
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 10
      Events:
        ApiEvent:
          Type: Api
          RestApiId: !Ref ApiGateway
          StageName: dev
          Properties:
            Path: /crypto-search
            Method: POST

Outputs:
  CryptoSearchFunction:
    Description: "API Gateway endpoint URL for CryptoSearchFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/crypto-search"
