name: Deploy Crypto Price and Crypto Search Services

on:
  push:
    branches:
      - main
    paths:
      - 'crypto-price/**'
      - 'crypto-search/**'

jobs:
  deploy:
    name: Deploy Crypto Price and Crypto Search
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies (crypto-price)
        run: npm install --prefix crypto-price

      - name: Install dependencies (crypto-search)
        run: npm install --prefix crypto-search

      - name: SAM Build Crypto Price
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Build Crypto Price
        run: sam build --template crypto-price/template.yaml

      - name: SAM Deploy Crypto Price
        run: |
          sam deploy \
            --stack-name crypto-price \
            --region ${{ secrets.AWS_SES_REGION }} \
            --s3-bucket ${{ secrets.AWS_S3_BUCKET }} \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: SAM Build Crypto Search
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Build Crypto Search
        run: sam build --template crypto-search/template.yaml

      - name: SAM Deploy Crypto Search
        run: |
          sam deploy \
            --stack-name crypto-search \
            --region ${{ secrets.AWS_SES_REGION }} \
            --s3-bucket ${{ secrets.AWS_S3_BUCKET }} \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}